import Providers from '@/components/providers'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Lexend } from 'next/font/google'
import { Footer, MenuBar } from 'tp-kit/components'
import Menu from '@/components/menu'

const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Menu/>
        <Providers font={lexend}>
          {children}
        </Providers>
        <Footer/>
      </body>
    </html>
  )
}
